### ISSUE TITLE
IllegalStateException: Scoop needs to be initialized first!

### ISSUE THREAD

**Issue by faizan321** [52inc/Scoops#10]
IllegalStateException: Scoop needs to be initialized first!

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    overridePendingTransition(0, 0);
    Scoop.getInstance().apply(this);
}
```

compiler says Scoop need to initialized first but i have initlized it by "Scoop.getInstance().apply(this);" what is wrong with it?

**Comment by r0adkll** [comment]
Please refer to this section of the Readme: https://github.com/52inc/Scoops#installation

**Comment by faizan321** [comment]
how to bind Accent ?

Scoop.getInstance().bind(this, Toppings.PRIMARY, mAppBar)
        .bindStatusBar(this, Toppings.PRIMARY_DARK).bind(this,
Toppings.ACCENT, ?);

**Comment by faizan321** [comment]
sorry! i have solved that issue. thank you for your help.

**Comment by faizan321** [comment]
thank u so much for quick reply.... i have another problem, i will be
thanks full to u if u give me solution.

java.security.InvalidParameterException: Nothing has been bound to the
Topping of the given id (2).

this error comes on passing primary colour, primary dark or accent colour.

**Comment by r0adkll** [comment]
Could you please post the full stacktrace?

**Comment by r0adkll** [comment]
Could you please open another issue and post the full stacktrace so I could further document and help you with your issue
