### ISSUE TITLE
primary color not work

### ISSUE THREAD

**Issue by changjiashuai** [52inc/Scoops#6]
primary color not work but change theme activity is work.

**Comment by r0adkll** [comment]
Are you referring to the `@BindTopping` annotation code? or about the primary color attribute in the themes themselves (i.e. the App Bar isn't updating color?)

**Comment by zrheasy** [comment]
you should add **Scoop.sugarCone().bind(this, Toppings.PRIMARY, mAppBar)
                .bindStatusBar(this, Toppings.PRIMARY_DARK);** @changjiashuai

**Comment by r0adkll** [comment]
I also just found a bug in the annotation processor that breaks when you don't specify a color adapter thus causing those elements not to update. I will be pushing an update soon but in the meantime you can just specify the `DefaultColorAdapter.class` in the annotation (or the manual way as demonstrated above)

**Comment by r0adkll** [comment]
v1.0.0 is now out and this should be officially resolved.
